[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "automated-sing-box-generator"
version = "0.3.11"
authors = [
  { name="henryliu443", email="henryliu443@gmail.com" },
]
description = "Sing-box + Cloudflare WARP 一键自动部署工具"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests",
]

[project.urls]
"Homepage" = "https://github.com/henryliu443/Automated-sing-box-json-generator"
"Bug Tracker" = "https://github.com/henryliu443/Automated-sing-box-json-generator/issues"

[project.scripts]
automated-sing-box-generator = "automated_sing_box_generator.cli:main"

[tool.setuptools.package-data]
automated_sing_box_generator = ["rules.json", "templates/*.template"]
